### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/magufl-instagram-post#1]
# Revisión - Aprobado
- [x] Estilo de código y limpieza
# Feedback
- ¡Muy buen trabajo. Felicidades @magufl !
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- El estilo inline en <body> (style="background-color: black;") puede ser movido al archivo de CSS para mantener el código más limpio y modular.
- La imagen del proyecto original no tiene los márgenes laterales.

**Comment by magufl** [comment]
ok

**Comment by EduardoHernandezGuzman** [comment]
Muy buen trabajo. A por el siguiente proyecto!!!
